export const FETCH_ADS_REQUEST = "FETCH_ADS_REQUEST";
export const FETCH_ADS_SUCCESS = "FETCH_ADS_SUCCESS";
export const FETCH_ADS_FAILURE = "FETCH_ADS_FAILURE";

export const SET_FILTERS = "SET_FILTERS";
export const FETCH_ADS_FILTERED = "FETCH_ADS_FILTERED";

export const ADD_TO_FAVS_REQUEST = "ADD_TO_FAVS_REQUEST";
export const ADD_TO_FAVS_SUCCESS = "ADD_TO_FAVS_SUCCESS";
export const ADD_TO_FAVS_FAILURE = "ADD_TO_FAVS_FAILURE";

export const REMOVE_FROM_FAVS = "REMOVE_FROM_FAVS";

export const CREATE_AD = "CREATE_AD";
export const EDIT_AD = "EDIT_AD";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
